name: Build & Push LunaTV Multi-Arch Image

on:
  workflow_dispatch:       # 手动触发按钮
  schedule:
    - cron: '0 0 * * *'    # 每天 0 点自动触发
  repository_dispatch:     # 接收上游触发事件

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 QEMU 支持多架构
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 3. 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. 登录 GHCR
      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u colaxr --password-stdin

      # 5. 拉取上游镜像
      - name: Pull upstream image
        run: docker pull ghcr.io/moontechlab/lunatv:latest

      # 6. 内联 Dockerfile 构建多架构镜像并推送
      - name: Build and push multi-arch image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/colaxr/lunatv:latest \
            --pull \
            --push \
            - <<EOF
FROM ghcr.io/moontechlab/lunatv:latest
EOF
