name: Sync LunaTV Image

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 0 * * *' # 每天 0 点兜底同步
  repository_dispatch: # 接收上游触发事件

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 登录 GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u colaxr --password-stdin

      - name: 拉取上游镜像
        run: docker pull ghcr.io/moontechlab/lunatv:latest

      - name: 打 tag 成自己的仓库地址
        run: docker tag ghcr.io/moontechlab/lunatv:latest ghcr.io/colaxr/lunatv:latest

      - name: 推送到自己的 GHCR
        run: docker push ghcr.io/colaxr/lunatv:latest
